In [22]:
%load_ext autoreload
%autoreload 2

import tensorflow as tf
import cv2
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [7]:
def parse_tfrecord_tf(record):
    features = tf.io.parse_single_example(record, features={
        'shape': tf.io.FixedLenFeature([3], tf.int64),
        'data': tf.io.FixedLenFeature([], tf.string)})
    data = tf.io.decode_raw(features['data'], tf.uint8)
    print(features['shape'])
    return tf.reshape(data, features['shape'])

In [28]:
raw_dataset = tf.data.TFRecordDataset("./celebahq/celebahq-r09.tfrecords")

for i, raw_record in enumerate(raw_dataset.take(100)):
    image_raw = tf.transpose(parse_tfrecord_tf(raw_record), [1, 2, 0]).numpy()
    image_raw = np.flip(image_raw, 2)
    #print(image_raw)
    cv2.imwrite(f"img{i}.jpg", image_raw)

tf.Tensor([  3 512 512], shape=(3,), dtype=int64)
tf.Tensor([  3 512 512], shape=(3,), dtype=int64)
tf.Tensor([  3 512 512], shape=(3,), dtype=int64)
tf.Tensor([  3 512 512], shape=(3,), dtype=int64)
tf.Tensor([  3 512 512], shape=(3,), dtype=int64)
tf.Tensor([  3 512 512], shape=(3,), dtype=int64)
tf.Tensor([  3 512 512], shape=(3,), dtype=int64)
tf.Tensor([  3 512 512], shape=(3,), dtype=int64)
tf.Tensor([  3 512 512], shape=(3,), dtype=int64)
tf.Tensor([  3 512 512], shape=(3,), dtype=int64)
tf.Tensor([  3 512 512], shape=(3,), dtype=int64)
tf.Tensor([  3 512 512], shape=(3,), dtype=int64)
tf.Tensor([  3 512 512], shape=(3,), dtype=int64)
tf.Tensor([  3 512 512], shape=(3,), dtype=int64)
tf.Tensor([  3 512 512], shape=(3,), dtype=int64)
tf.Tensor([  3 512 512], shape=(3,), dtype=int64)
tf.Tensor([  3 512 512], shape=(3,), dtype=int64)
tf.Tensor([  3 512 512], shape=(3,), dtype=int64)
tf.Tensor([  3 512 512], shape=(3,), dtype=int64)
tf.Tensor([  3 512 512], shape=(3,), dtype=int64)
